---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_ssh_host_key_checking: false
    - host_key_checking: false
    - ssh_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    - ANSIBLE_HOST_KEY_CHECKING: false
  roles:
    - deploy
    - configure-prometheus-node-exporter
