---
- name: "Copy files to the host"
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu
- name: "mkdir for the extracted file"
  command: mkdir /home/ubuntu/backend
- name: "Untar the source"
  command: tar -xvf /home/ubuntu/artifact.tar.gz -C /home/ubuntu/backend
- nanme: "Go to the right directory"
  command: chdir=/home/ubuntu/backend
- name: "Install npm"
  command: npm install
- name: "Stop the default pm2"
  command: pm2 stop default
- name: "Start npm pm2"
  command: pm2 start npm -- start

