---
- name: "Copy files to the host"
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu
- name: "Untar the source"
  command: tar -xvzf community_images.tar.gz -C backend
- name: "Install npm"
  command: npm install
- name: "Stop the default pm2"
  command: pm2 stop default
- name: "Start npm pm2"
  command: pm2 start npm -- start

