---
- name: "Copy files to the host"
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu
- name: "mkdir for the extracted file"
  file:
    path: /home/ubuntu/backend
    state: directory
- name: "Untar the source"
  command: tar -xvf /home/ubuntu/artifact.tar.gz -C /home/ubuntu/backend
- name: "Go to the right directory"
  command: chdir=/home/ubuntu/backend ls
- name: "Install npm"
  command: npm install
- name: "Copy the .env file"
  copy:
    src: files/example.env
    dest: /home/ubuntu/backend/.env
- name: "kill any pm2"
  command: pm2 kill 
- name: "compile code"
  command: npm run build
- name: "Start npm pm2"
  command: pm2 start npm -- start 

