---
- name: "Install curl"
  become: true
  command: apt install curl
- name: "Add the key"
  command: curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
  args:
    warn: false
- name: "Add the repo"
  command: apt-get install -y nodejs npm
- name: "Install pm2"
  command: npm i -g pm2 
  