---
- name: node play 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  

  tasks:
  - name: "Add the key"
    command: curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
  - name: "Add the repo"
    command: apt-get install -y nodejs npm
  - name: "Install pm2"
    command: npm i -g pm2 
    